[build]
  publish = "public"

[[redirects]]
  from = "/post7"
  to = "/post7-entry.html"
  status = 200

[[redirects]]
  from = "/post1"
  to = "/post1-exit.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
